name       : jq
version    : 1.6
release    : 7
source     :
    - https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz : 5de8c8e29aaa3fb9cc6b47bb27299f271354ebb72514e3accadc7d38b5bbaa72
homepage   : https://stedolan.github.io/jq/
license    : MIT
component  : programming.tools
summary    : jq is a lightweight and flexible command-line JSON processor
description: |
    jq is a lightweight and flexible command-line JSON processor.
builddeps  :
    - pkgconfig(oniguruma)
setup      : |
    %configure \
      --disable-maintainer-mode \
      --disable-static
build      : |
    %make
install    : |
    %make_install
