name       : jq
version    : 1.5
release    : 1
source     :
    - https://github.com/stedolan/jq/archive/jq-1.5.tar.gz : d5667641d28c27d0c1e70de83e7f9bd8b2fed7fbf6a1d68731177d400a533c65
license    : BSD-2-Clause
component  : programming
summary    : jq is a lightweight and flexible command-line JSON processor
description: |
    jq is a lightweight and flexible command-line JSON processor.
setup      : |
    %reconfigure --disable-maintainer-mode --disable-static
build      : |
    %make
install    : |
    %make_install
