name       : jq
version    : '1.7'
release    : 9
source     :
    - https://github.com/jqlang/jq/releases/download/jq-1.7/jq-1.7.tar.gz : 402a0d6975d946e6f4e484d1a84320414a0ff8eb6cf49d2c11d144d4d344db62
homepage   : https://stedolan.github.io/jq/
license    : MIT
component  : programming.tools
summary    : jq is a lightweight and flexible command-line JSON processor
description: |
    jq is a lightweight and flexible command-line JSON processor akin tosed,awk,grep, and friends for JSON data. It's written in portable C and has zero runtime dependencies, allowing you to easily slice, filter, map, and transform structured data.
builddeps  :
    - pkgconfig(oniguruma)
setup      : |
    %configure \
      --disable-maintainer-mode \
      --disable-static
build      : |
    %make
install    : |
    %make_install
